### PR TITLE
src: update to hyper 0.12

### PR DESCRIPTION
**Pull request by lucab**
This updates to hyper 0.12 and tokio-rustls 0.6, getting rid of
tokio-proto support.

Fixes: https://github.com/ctz/hyper-rustls/issues/39
Fixes: https://github.com/ctz/hyper-rustls/issues/40

### CODE REVIEW

**Comment by kpcyrd** [comment]
I've tested this PR and it resolves both #39 and #40.

**Comment by ctz** [comment]
Thank you for the work and testing on this :)

**Comment by kpcyrd** [comment]
@ctz can we get a new release so we can upgrade to hyper 0.12? :)

**Comment by ctz** [comment]
Yep, 0.13 is up.

**Pull request merged**
