### PR TITLE
Allow getting at underlying rustls::Session

### PR DESCRIPTION
**Pull request by ctz**

### CODE REVIEW

**Comment by alex** [comment]
Unfortunately this doesn't work for me, this requires a mutable borrow of the `WrappedStream`, which one doesn't have when using `request.ssl()`: https://hyper.rs/hyper/v0.10.9/hyper/server/request/struct.Request.html#method.ssl

**Comment by alex** [comment]
btw, thanks for jumping on this so quickly!

**Comment by ctz** [comment]
> Unfortunately this doesn't work for me

Oops! Try now.

**Comment by alex** [comment]
Perfect! Works great now, thanks!

**Pull request merged**
