### PR TITLE
cargo: update hyper to 0.11

### PR DESCRIPTION
**Pull request by lucab**
hyper-0.11 has been released, with tokio-based async support!

This PR updates to the released hyper version, and rebases the whole `current-hyper` branch on top of master.

### CODE REVIEW

**Comment by lucab** [comment]
Great, thanks! Would you consider a `0.7` release of this crate? That would unblock all reverse dependencies to be publishable as uploaded crates.

**Comment by ctz** [comment]
Yep, doing that just now. I was trying to work out why travis was being crazy.

**Comment by lucab** [comment]
Yup, see https://github.com/ctz/hyper-rustls/commit/96f496e0b9b12c9ea8f5a10c877420a55c84d82c#commitcomment-22547755

**Comment by ctz** [comment]
0.7.0 published

**Pull request merged**
