### PR TITLE
 Update to rustls 0.12 

### LINKED ISSUE #37: ring compilation broken on latest nightly
Maybe,  ring dependency should be updated on the next release(0.13) so it compiles with future versions of compiler? https://github.com/briansmith/ring/issues/609

### PR DESCRIPTION
**Pull request by crawford**
This is needed in order to fix some recent breakage in ring on nightly
builds.

Fixes #37.

### CODE REVIEW

**Comment by crawford** [comment]
Friendly bump.

**Comment by ctz** [comment]
Thanks! I'll push the release at the end of this week when I'm done travelling.

**Comment by alex** [comment]
Thanks 🎉 !

**Comment by mati865** [comment]
https://github.com/rust-lang/rust/pull/47392 has been merged so new nightly versions will be fine even without version bump.

**Comment by ctz** [comment]
https://crates.io/crates/hyper-rustls/0.12.0

**Pull request merged**
