### PR TITLE
WIP: Futures 0.3

### PR DESCRIPTION
**Pull request by markuskobler**
Building on top of #79 
Would not make sense to merge until hyper 0.13 gets released.

### CODE REVIEW

**Comment by dbcfd** [comment]
Closed my PR. Let me know if you want help with this. Was using it to move this forward https://github.com/seanmonstar/reqwest/pull/592

**Comment by alex** [comment]
Upstream `hyper` has had an API change, `HttpConnector::new()` no longer takes any arguments.

Can you update this? It should just be a matter of not passing `threads` at `src/connector.rs` line 28.

**Comment by dbcfd** [comment]
@markuskobler Updated my branch if you just want to merge that in.

**Comment by alex** [comment]
@markuskobler I sent a PR to your PR here https://github.com/markuskobler/hyper-rustls/pull/1 :-)

**Comment by theduke** [comment]
Hyper published a `0.13` alpha, would be great to get this moving.

**Comment by alex** [comment]
I sent a PR to this PR bumping to that.

**Comment by ctz** [comment]
Thanks for the work here. I've:

- taken this PR to jbp-async
- applied the above PR taking the hyper alpha
- make a couple of small changes to the examples to get them to compile with async (around `TcpListener`)
- published v0.18.0-alpha.1

I suggest we leave this PR live until this can be put on master (shortly after 1.39). I'll continue to take commits from this PR onto my branch, and make alpha releases from there if that's useful.

**Comment by theduke** [comment]
@ctz awesome, thanks.

**Comment by ctz** [comment]
Published 0.18.0-alpha.2

**Comment by ctz** [comment]
Thanks, this is on master now.

**Pull request closed without merging**
